version: 0.2

phases:
  install:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
      # if using static export:
      - npm run export || true
artifacts:
  base-directory: out
  files:
    - '**/*'